### ISSUE TITLE
Invalid Token Address Error

### ISSUE THREAD

**Issue by Eloonpooch** [blkcn-dev/front-run-pancakeswap-bot#1]
Hi
when i am trying to run the bot it checks everything and then gives error Invalid Token Address . Please suggest what is wrong

**Comment by blkcn-dev** [comment]
https://github.com/blkcn-dev/frontrun-pancakeswap-bot/blob/4980296bde8f16c1c34fed4bb89be5870a18b8e7/frontrun.js#L651

Uncomment this line. It may require to get and provide a new api bscan key.
